### ISSUE TITLE
config examples?

### ISSUE THREAD

**Issue by ywpkwon** [octobanana/peaclock#17]
So awesome project! I have one question. The main page says there are some config examples in `config/` but it seems there's only 'default' one. Where can I find more? How can I get this for example?
![Screenshot-2020-03-22T16:25:14-07:00](https://user-images.githubusercontent.com/18429284/77265424-e2babf00-6c59-11ea-8c0e-20619c4717b1.png)

**Comment by octobanana** [comment]
Oops! I'll push the other config examples tonight and let you know which one corresponds to the above picture.

Thanks for catching that!

**Comment by ywpkwon** [comment]
Thanks for your support! Please also include an example similar as in the screenshot :)

**Comment by octobanana** [comment]
It turned out there was an issue with the text rendering when the foreground colour was set to party mode, so it took a bit longer then expected. It should be all good now!

Make sure to update to the latest version, [0.4.1](https://github.com/octobanana/peaclock/releases/tag/0.4.1). Check out the release notes, as the build script has changed.

The [binary-party](https://github.com/octobanana/peaclock/blob/master/cfg/binary-party) config example is the one used in the above screenshot.

Let me know how it works out :)

**Comment by ywpkwon** [comment]
This works great! Thank you so much. (I have a question about unicode characters but I'll ask in another post.)
